import Head from "next/head";
import { useState } from "react"
import axios from 'axios'
import { BsArrowReturnLeft } from "react-icons/bs"
import Link from "next/link";

import styles from "@/styles/Signup.module.css";
import styles2 from "@/styles/Home.module.css"

export default function Signup() {
  const [customer, setCuctomer] = useState({})

  const handleSignup = (e) => {
    console.log(customer)
    axios.post('/api/customer/signup', customer).then((response) => {
      console.log(response)
      const {data} = response
      if(data.code == 200){
        window.location.replace('/Login')
      }else{
        console.log(err)
      }
    }).catch((err) => {
      console.log(err)
    })
  }

  return <>
    <Head>
      <title>Đăng Ký</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="ico" href="/favicon.ico"></link>
    </Head>
    <nav className={styles2.nav}>
      <div className={styles2.logo}>
        <div className={styles2.text}>VeChai</div>
      </div>
      <div>
        <ul className={styles2.list1}>
          <li><Link className={styles2.linknav} href="/Home">
            <BsArrowReturnLeft style={{ marginRight: '5px' }} />Quay Về Trang Chủ</Link></li>
        </ul>
      </div>
    </nav>
    <form className={styles.signup}>
      <h1 className={styles.textSignup}>Đăng Ký Tài Khoản</h1>
      <div className=" form-outline mb-4">
        <input
          type="text"
          id="form2Example1"
          className="form-control"
          value={customer.fullname}
          onChange={(e) => setCuctomer(
            {
              ...customer,
              fullname: e.target.value
            }
          )}
          placeholder={"Tên người dùng"}
        />
      </div>
      <div className="form-outline mb-4">
        <select name="user" id="user" style={{ border: '1px solid #dee2e6a3', height: '36px', borderRadius: '6px', color: 'GrayText' }}>
          <option value="Người cần bán ve chai">Người cần bán ve chai</option>
          <option value="Chủ vựa ve chai">Chủ vựa ve chai</option>
          <option value="Người thu mua ve chai">Người thu mua ve chai</option>
        </select>
      </div>
      <div className="form-outline mb-4">
        <input
          type="email"
          id="form2Example1"
          className="form-control"
          value={customer.email}
          onChange={(e) => setCuctomer(
            {
              ...customer,
              email: e.target.value
            }
          )}
          placeholder={"Địa chỉ Email"}
        />
      </div>

      <div className="form-outline mb-4">
        <input
          type="password"
          id="form2Example2"
          className="form-control"
          value={customer.password}
          onChange={(e) => setCuctomer(
            {
              ...customer,
              password: e.target.value
            }
          )}
          placeholder={"Mật khẩu"}
        />
      </div>

      <div className="form-outline mb-4">
        <input
          type="password"
          id="form2Example2"
          className="form-control"
          placeholder={"Nhập lại mật khẩu"}
        />
      </div>

      <button
        type="button"
        className="btn-đk btn-block mb-4"
        onClick={handleSignup}
      >
        Đăng Ký
      </button>

    </form>
  </>
} 