import Head from 'next/head';
import Link from 'next/link';

import styles from '@/styles/Login.module.css';

export default function Login() {
    return <>
        <Head>
            <title>Trang chủ</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="ico" href="/favicon.ico"></link>
        </Head>
        <div className={styles.Login}>
        <h1 className={styles.textLogin}>Đăng Nhập</h1>
        <form className={styles.fromLogin}>
          <div className="form-outline mb-4">
            <input
              type="text"
              id="form2Example1"
              className="form-control"
              placeholder={"Tên đăng nhập"}
            />
            <label className={styles.formLabel} htmlFor="form2Example1">
              *
            </label>
          </div>

          <div className="form-outline mb-4">
            <input
              type="password"
              id="form2Example2"
              className="form-control"
              placeholder={"Mật khẩu"}
            />
            <label className={styles.formLabel} htmlFor="form2Example2">
              *
            </label>
          </div>

          <div className="row mb-2">
            <div className="col">
              <Link className={styles.dktk} href="/Signup" style={{ fontSize: "1rem" }}>
                Đăng ký tài khoản mới!
              </Link>
            </div>
          </div>

          <button
            onClick={() => {
            //   submit();
            }}
            type="button"
            className="btn-đn btn-block mb-4"
          >
            Đăng nhập
          </button>
        </form>
        </div>
    </>

} 