import Head from "next/head";
import { useState, useEffect } from "react";
import Layout from "@/components/layout";
import Axios from '@/helper/axios.helper';
import axios from "axios";
import _ from 'lodash'
import { pages } from '@/utils/contanst'

import PostDashboard from "@/components/postDashboard";

export async function getServerSideProps({ req, res }) {
    const token = req.cookies["vechaitoken"];
    const { data: userData } = await Axios({
        url: "/api/customer/getbytoken",
        method: "GET",
        headers: { authorization: token },
    })

    return {
        props: {
            userData: userData[0]
        },
    };
}

export default function Dashboard({ userData }) {
    const { fullname, name, email, accessApp } = userData

    const [layoutPages, setLayoutPages] = useState([])
    const [posts, setPosts] = useState([])

    useEffect(() => {
        axios.get("/api/post?limit=5").then((res) => {
            console.log(res);
            if (res && res.data) {
                const { data } = res.data;
                setPosts(data);
            }
        });
    }, []);

    useEffect(() => {
        const accessAppsList = accessApp.split(', ')
        console.log(accessAppsList)
        if (accessAppsList && Array.isArray(accessAppsList)) {
            const userPages = _.filter(pages, (page) => {
                return accessAppsList.includes(page.key)
            })
            setLayoutPages(userPages)
        }
    }, [])

    return (
        <>
            <Head>
                <title>Các bài đăng</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="ico" href="/favicon.ico"></link>
            </Head>
            <main>
                <Layout pages={layoutPages} user={{ fullname, name, email }}>
                    <h2 style={{padding: "10px", color: "gray"}}>Các Bài Đăng Về Thanh Lý VeChai</h2>

                    <PostDashboard posts={posts} ></PostDashboard>
                </Layout>
            </main>
        </>
    );
}