import Head from 'next/head';
import Script from 'next/script';
import Link from 'next/link';
import { useState } from 'react';
import axios from 'axios';
import { BsSun, BsFillMoonStarsFill, BsFillBellFill,BsFillGridFill } from "react-icons/bs"


export default function Dashboard() {

    

    const handelLogout = () =>{
        setCookie('vechaitoken', '')
        window.location.reload()

    }

    const setCookie = (cname, cvalue, exdays) => {
        const d = new Date();
        d.setTime(d.getTime() + (exdays*24*60*60*1000));
        let expires = "expires="+ d.toUTCString();
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
      }


    return <>
        <Head>
            <title>Trang chủ</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="ico" href="/favicon.ico"></link>
        </Head>
        <main>
            {/* <!-- Dashboard --> */}
            <div class="dashboard">
                {/* <!-- Sidebar --> */}
                <div class="sidebar flex-c flex-sb">
                    <div class="brand">VeChai</div>
                    <div class="side-nav">
                        <div class="menu-item flex active">
                            <div class="icon">
                                <BsFillGridFill/>
                            </div>

                            <p>Dashboard</p>
                        </div>

                      </div>
                    <div class="log-out">
                        <div class="menu-item flex" onClick={handelLogout}>
                            <div class="icon">
                                <ion-icon name="log-out-outline"></ion-icon>
                            </div>

                            <p>Logout</p>
                        </div>
                    </div>
                </div>
                {/* <!-- End Sidebar --> */}

                {/* <!-- Dashboard Content --> */}
                <div class="dashboard-content">
                    {/* <!-- ======Topbar======= --> */}
                    <div class="topbar flex flex-sb">
                        <div class="search flex">
                            <div class="icon">
                                <ion-icon name="search-outline"></ion-icon>
                            </div>
                            <input type="text" placeholder=" Search any collection" />
                        </div>

                        <div class="theme flex">
                            <div class="dark flex">
                                <BsFillMoonStarsFill/>
                            </div>
                            <div class="light active flex">
                               <BsSun/>
                            </div>
                        </div>

                        <div class="notification icon">
                            <BsFillBellFill/>
                        </div>

                        <div class="user flex flex-sb">
                            <img
                                src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                alt=""
                            />
                            <p>Hassnain</p>
                            <ion-icon name="chevron-down-outline"></ion-icon>
                        </div>
                    </div>
                    {/* <!-- ======End Topbar======= --> */}

                    {/* <!-- ======Section======= --> */}
                    <div class="section flex flex-sb">
                        {/* <!-- Section Left --> */}
                        <div class="section-left">
                            {/* <!-- ======Banner======= --> */}
                            <div class="banner flex flex-sb">
                                <div class="text">
                                    <h2>
                                        Dicover and sell <br />
                                        your own NFTs
                                    </h2>

                                    <a href="#" class="btn">
                                        Discover Now
                                    </a>
                                </div>

                                <img
                                    src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/banner.svg"
                                    alt=""
                                />
                            </div>

                            <div class="nfts">
                                <div class="trending heading flex flex-sb">
                                    <h2>Trending NFTs</h2>
                                    <p>See all</p>
                                </div>

                                {/* <!-- ======Categories======= --> */}

                                <div class="categories flex flex-sb">
                                    <div class="category flex">
                                        <div class="icon">🔥</div>
                                        <p>Trending</p>
                                    </div>

                                    <div class="category flex">
                                        <div class="icon">🎨</div>
                                        <p>Art</p>
                                    </div>

                                    <div class="category flex">
                                        <div class="icon">🕹️</div>
                                        <p>Game</p>
                                    </div>

                                    <div class="category flex">
                                        <div class="icon">👗</div>
                                        <p>Fashion</p>
                                    </div>

                                    <div class="category flex">
                                        <div class="icon">🎵</div>
                                        <p>Music</p>
                                    </div>
                                </div>

                                {/* <!-- =====Browse NFT===== --> */}
                                <div class="browse">
                                    <div class="nft">
                                        <img
                                            src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-1.jpg"
                                            alt=""
                                        />
                                        <div class="title">Weary Artwork</div>
                                        <div class="details flex flex-sb">
                                            <div class="author flex">
                                                <img
                                                    src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                                    alt=""
                                                />
                                                <p>Hassnain Haider</p>
                                            </div>
                                            <div class="price">4.5 ETH</div>
                                        </div>
                                    </div>

                                    <div class="nft">
                                        <img
                                            src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-2.jpg"
                                            alt=""
                                        />
                                        <div class="title">Spectrum of Color</div>
                                        <div class="details flex flex-sb">
                                            <div class="author flex">
                                                <img
                                                    src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                                    alt=""
                                                />
                                                <p>Hassnain Haider</p>
                                            </div>
                                            <div class="price">4 ETH</div>
                                        </div>
                                    </div>

                                    <div class="nft">
                                        <img
                                            src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-3.jpg"
                                            alt=""
                                        />
                                        <div class="title">Vivid Artwork</div>
                                        <div class="details flex flex-sb">
                                            <div class="author flex">
                                                <img
                                                    src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                                    alt=""
                                                />
                                                <p>Hassnain Haider</p>
                                            </div>
                                            <div class="price">3.5 ETH</div>
                                        </div>
                                    </div>

                                    <div class="nft">
                                        <img
                                            src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/nft-4.jpg"
                                            alt=""
                                        />
                                        <div class="title">Nature's Love</div>
                                        <div class="details flex flex-sb">
                                            <div class="author flex">
                                                <img
                                                    src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                                    alt=""
                                                />
                                                <p>Hassnain Haider</p>
                                            </div>
                                            <div class="price">5 ETH</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* <!-- Section Right --> */}
                        <div class="section-right">
                            <div class="graph flex-c">
                                <p>Balance</p>
                                <h2>93,565.00</h2>

                                <img
                                    src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/graph.svg"
                                    alt=""
                                />
                            </div>

                            <div class="top-creators">
                                <div class="heading flex flex-sb">
                                    <h2>Top Creators</h2>
                                    <p>See all</p>
                                </div>

                                <div class="creator flex flex-sb">
                                    <div class="follow-creator flex">
                                        <img
                                            src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                            alt=""
                                        />
                                        <div class="creator-details">
                                            <h3>Hassnain Haider</h3>
                                            <p>@hassnain</p>
                                        </div>
                                    </div>

                                    <a href="#" class="btn following">
                                        Following
                                    </a>
                                </div>

                                <div class="creator flex flex-sb">
                                    <div class="follow-creator flex">
                                        <img
                                            src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                            alt=""
                                        />
                                        <div class="creator-details">
                                            <h3>Hassnain Haider</h3>
                                            <p>@hassnain</p>
                                        </div>
                                    </div>

                                    <a href="#" class="btn follow following">
                                        Follow
                                    </a>
                                </div>

                                <div class="creator flex flex-sb">
                                    <div class="follow-creator flex">
                                        <img
                                            src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                            alt=""
                                        />
                                        <div class="creator-details">
                                            <h3>Hassnain Haider</h3>
                                            <p>@hassnain</p>
                                        </div>
                                    </div>

                                    <a href="#" class="btn follow following">
                                        Follow
                                    </a>
                                </div>

                                <div class="creator flex flex-sb">
                                    <div class="follow-creator flex">
                                        <img
                                            src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                            alt=""
                                        />
                                        <div class="creator-details">
                                            <h3>Hassnain Haider</h3>
                                            <p>@hassnain</p>
                                        </div>
                                    </div>

                                    <a href="#" class="btn follow following">
                                        Follow
                                    </a>
                                </div>

                                <div class="creator flex flex-sb">
                                    <div class="follow-creator flex">
                                        <img
                                            src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                            alt=""
                                        />
                                        <div class="creator-details">
                                            <h3>Hassnain Haider</h3>
                                            <p>@hassnain</p>
                                        </div>
                                    </div>

                                    <a href="#" class="btn follow following">
                                        Follow
                                    </a>
                                </div>

                                <div class="creator flex flex-sb">
                                    <div class="follow-creator flex">
                                        <img
                                            src="https://raw.githubusercontent.com/programmercloud/nft-dashboard/main/img/user.png"
                                            alt=""
                                        />
                                        <div class="creator-details">
                                            <h3>Hassnain Haider</h3>
                                            <p>@hassnain</p>
                                        </div>
                                    </div>

                                    <a href="#" class="btn follow following">
                                        Follow
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {/* <!-- ======End Section======= --> */}
                </div>
                {/* <!-- End Dashboard Content --> */}
            </div>
            {/* <!-- End Dashboard --> */}
        </main>
        <Script src="/js/dashboard.js"></Script>
    </>

} 